### ISSUE TITLE
A suggestion about python code of baseline methods.

### ISSUE THREAD

**Issue by yeqing97** [nongdaxiaofeng/DDAPRED#1]
Hi! @nongdaxiaofeng 
In the work 'DDAPRED: a computational method for predicting drug repositioning using regularized logistic matrix factorization', you have compared your method with two baseline algorithms. Could you please share the scripts of these methods so that I can reproduce the experiments in your paper?

**Comment by nongdaxiaofeng** [comment]
Sorry, I have no scripts of the two algorithms. Because I used the same datasets as them, I used their results directly.

















At 2021-02-09 22:31:34, "Damen" <notifications@github.com> wrote:

Hi! @nongdaxiaofeng
In the work 'DDAPRED: a computational method for predicting drug repositioning using regularized logistic matrix factorization', you have compared your method with two baseline algorithms. Could you please share the scripts of these methods so that I can reproduce the experiments in your paper?

**Comment by yeqing97** [comment]
> Sorry, I have no scripts of the two algorithms. Because I used the same datasets as them, I used their results directly. At 2021-02-09 22:31:34, "Damen" <notifications@github.com> wrote: Hi! @nongdaxiaofeng In the work 'DDAPRED: a computational method for predicting drug repositioning using regularized logistic matrix factorization', you have compared your method with two baseline algorithms. Could you please share the scripts of these methods so that I can reproduce the experiments in your paper? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for your reply! Do you mean that you used the predicted score in 'Supplementary Data 2' to calculate the ROC_AUC ?

**Comment by nongdaxiaofeng** [comment]
SCMFDD reported the AUCs of LRSSL and SCMFDD on the LRSSL dataset in its published paper, and I used the reported AUCs.




















At 2021-02-16 09:55:46, "Damen" <notifications@github.com> wrote:

Sorry, I have no scripts of the two algorithms. Because I used the same datasets as them, I used their results directly. At 2021-02-09 22:31:34, "Damen" notifications@github.com wrote: Hi! @nongdaxiaofeng In the work 'DDAPRED: a computational method for predicting drug repositioning using regularized logistic matrix factorization', you have compared your method with two baseline algorithms. Could you please share the scripts of these methods so that I can reproduce the experiments in your paper? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for your reply! Do you mean that you used the predicted score in 'Supplementary Data 2' to calculate the ROC_AUC ?

**Comment by yeqing97** [comment]
> SCMFDD reported the AUCs of LRSSL and SCMFDD on the LRSSL dataset in its published paper, and I used the reported AUCs. At 2021-02-16 09:55:46, "Damen" <notifications@github.com> wrote: Sorry, I have no scripts of the two algorithms. Because I used the same datasets as them, I used their results directly. At 2021-02-09 22:31:34, "Damen" notifications@github.com wrote: Hi! @nongdaxiaofeng In the work 'DDAPRED: a computational method for predicting drug repositioning using regularized logistic matrix factorization', you have compared your method with two baseline algorithms. Could you please share the scripts of these methods so that I can reproduce the experiments in your paper? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Thanks for your reply! Do you mean that you used the predicted score in 'Supplementary Data 2' to calculate the ROC_AUC ? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

![image](https://user-images.githubusercontent.com/44990275/108011040-31770180-7041-11eb-8bf8-c458ff7c48f4.png)
In the figure 2 of your paper, you have drawn the ROC curve of the DTINet. I'm a little bit confused that how to draw the curve without the exact prediction scores.

**Comment by nongdaxiaofeng** [comment]
I implement DTINet on the drug-disease association dataset. The source code of DTINet can be found by searching DTINet in Github.













At 2021-02-16 10:32:07, "Damen" <notifications@github.com> wrote:

SCMFDD reported the AUCs of LRSSL and SCMFDD on the LRSSL dataset in its published paper, and I used the reported AUCs. At 2021-02-16 09:55:46, "Damen" notifications@github.com wrote: Sorry, I have no scripts of the two algorithms. Because I used the same datasets as them, I used their results directly. At 2021-02-09 22:31:34, "Damen" notifications@github.com wrote: Hi! @nongdaxiaofeng In the work 'DDAPRED: a computational method for predicting drug repositioning using regularized logistic matrix factorization', you have compared your method with two baseline algorithms. Could you please share the scripts of these methods so that I can reproduce the experiments in your paper? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Thanks for your reply! Do you mean that you used the predicted score in 'Supplementary Data 2' to calculate the ROC_AUC ? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.


In the figure 2 of your paper, you have drawn the ROC curve of the DTINet. I'm a little bit confused that how to draw the curve without the exact prediction scores.

**Comment by yeqing97** [comment]
> I implement DTINet on the drug-disease association dataset. The source code of DTINet can be found by searching DTINet in Github. At 2021-02-16 10:32:07, "Damen" <notifications@github.com> wrote: SCMFDD reported the AUCs of LRSSL and SCMFDD on the LRSSL dataset in its published paper, and I used the reported AUCs. At 2021-02-16 09:55:46, "Damen" notifications@github.com wrote: Sorry, I have no scripts of the two algorithms. Because I used the same datasets as them, I used their results directly. At 2021-02-09 22:31:34, "Damen" notifications@github.com wrote: Hi! @nongdaxiaofeng In the work 'DDAPRED: a computational method for predicting drug repositioning using regularized logistic matrix factorization', you have compared your method with two baseline algorithms. Could you please share the scripts of these methods so that I can reproduce the experiments in your paper? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Thanks for your reply! Do you mean that you used the predicted score in 'Supplementary Data 2' to calculate the ROC_AUC ? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. In the figure 2 of your paper, you have drawn the ROC curve of the DTINet. I'm a little bit confused that how to draw the curve without the exact prediction scores. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks! I got it.
